terraform {
  required_version = ">= 1.3.0"
  
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
  }
}

provider "aws" {
  region = var.aws_region

}

# creates a random ID ,so your seccret name is uniue
resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

# AWS Secrets Manager - Store SSH Private Key// craetes an empty secrete in amazon secret manager
resource "aws_secretsmanager_secret" "ssh_key" {
  name                    = "${var.project_name}-ssh-key-${random_string.suffix.result}"
  description             = "SSH private key - stored securely, never in Git"
  recovery_window_in_days = 7 # Days before permanent deletion

  tags = {
    Name        = "${var.project_name}-ssh-key"
    Project     = var.project_name
    Environment = var.environment
    ManagedBy   = "Terraform"
  }
}

# Placeholder secret version (will be updated by script)
resource "aws_secretsmanager_secret_version" "ssh_key" {
  secret_id = aws_secretsmanager_secret.ssh_key.id

  secret_string = jsonencode({
    private_key = "PLACEHOLDER - Run scripts/generate-and-upload-key.sh"
    public_key  = "PLACEHOLDER"
    key_type    = "ed25519"
    created_at  = timestamp()
    note        = "Generated by Terraform, updated by script"
  })

  lifecycle {
    ignore_changes = [secret_string] # Don't overwrite when script updates
  }
}

# IAM Policy Document - Read secret
data "aws_iam_policy_document" "read_secret" {
  statement {
    sid    = "ReadSSHSecret"
    effect = "Allow"
    actions = [
      "secretsmanager:GetSecretValue",
      "secretsmanager:DescribeSecret"
    ]
    resources = [
      aws_secretsmanager_secret.ssh_key.arn
    ]
  }
}

# IAM Policy - Can be attached to EC2 roles
resource "aws_iam_policy" "read_ssh_secret" {
  name        = "${var.project_name}-read-ssh-secret-${random_string.suffix.result}"
  description = "Allow reading SSH key from Secrets Manager"
  policy      = data.aws_iam_policy_document.read_secret.json

  tags = {
    Name    = "${var.project_name}-read-ssh-secret-policy"
    Project = var.project_name
  }
}

# Example: IAM Role for EC2 (optional)
resource "aws_iam_role" "ec2_with_secrets" {
  name = "${var.project_name}-ec2-role-${random_string.suffix.result}"

  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Principal = {
          Service = "ec2.amazonaws.com"
        }
        Action = "sts:AssumeRole"
      }
    ]
  })

  tags = {
    Name    = "${var.project_name}-ec2-role"
    Project = var.project_name
  }
}

# Attach the secrets policy to the role
resource "aws_iam_role_policy_attachment" "ec2_secrets_access" {
  role       = aws_iam_role.ec2_with_secrets.name
  policy_arn = aws_iam_policy.read_ssh_secret.arn
}
